# Generated by Django 4.1.4 on 2023-01-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_alter_goalcategory_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Описание"
            ),
        ),
    ]
