# Generated by Django 4.1.4 on 2023-01-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="tg_chat_id",
            field=models.BigIntegerField(verbose_name="ID чата в телеграм"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_user_id",
            field=models.BigIntegerField(verbose_name="ID пользователя в телеграм"),
        ),
    ]
